### ISSUE TITLE
Undo Redo command

### ISSUE THREAD

**Issue by Wincenttjoi** [AY2021S1-CS2103T-T12-1/tp#130]
- [x] Wrap up implementation
- [x] Unit and integration tests

**Comment by Choo-Xing-Yu** [comment]
as discussed with @halcon-blanco , we feel that having a wrapper class that holds instantiation of both DeliveryModel and InventoryModel is better than having to use instanceof to check and having to overload the Command#execute method due to huge amount of repetition of code

Following the wrapper class idea adheres to SLAP principle more than the latter solution

@AY2021S1-CS2103T-T12-1/developers FYI
